import type { Training } from '../../models';
export const SEED_TRAINING: Training[] = [
  {
    id: 'train-001', title: 'Welcome to ASG', category: 'onboarding',
    summary: 'An introduction to Amplify Solutions Group, our values, and what we do.',
    content: 'ASG is a leading provider of financial and advisory services in Australia. This training covers our company history, our core values of integrity, innovation, and client focus, and how the Brisbane office operates day-to-day.',
    steps: ['Read the ASG company overview document', 'Watch the welcome video (link in resources)', 'Review the office floor plan and team locations', 'Complete the acknowledgement below'],
    estimatedMinutes: 30, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-002', title: 'Answering Incoming Calls', category: 'procedures',
    summary: 'Learn the ASG telephone greeting protocol and call handling procedures.',
    content: 'Every call is an opportunity to represent ASG. This module covers the standard greeting, hold procedures, and transferring calls. Always answer within three rings, greet the caller with "Good morning/afternoon, ASG Brisbane Reception," and speak clearly.',
    steps: ['Memorise the standard greeting script', 'Practice putting callers on hold', 'Learn how to transfer calls using the phone system', 'Practice taking messages (see Taking Accurate Messages training)', 'Role-play difficult call scenarios'],
    estimatedMinutes: 20, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-003', title: 'Taking Accurate Messages', category: 'procedures',
    summary: 'How to record complete and accurate phone messages every time.',
    content: 'Accurate messages are critical to ASG\'s client service. Always capture: caller\'s full name, company, phone number, time of call, nature of the message, urgency level, and any call-back instructions. Repeat the details back to confirm.',
    steps: ['Learn the six key message fields', 'Practice writing messages from sample calls', 'Learn the urgency classification system', 'Understand when to escalate vs. take a message'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-004', title: 'Booking and Changing Appointments', category: 'procedures',
    summary: 'Manage the ASG calendar and appointment booking process.',
    content: 'Appointments are managed through Google Calendar. This module covers creating events, checking staff availability, handling changes, and confirming bookings with clients. Always double-check time zones for interstate clients.',
    steps: ['Log into Google Calendar', 'Create a new appointment with all required fields', 'Check staff availability before booking', 'Practice rescheduling and cancelling appointments', 'Send calendar invites to clients when required'],
    estimatedMinutes: 20, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-005', title: 'Using the CRM', category: 'systems',
    summary: 'Navigate the ASG CRM system for reception tasks.',
    content: 'The CRM is used to log client interactions, update contact details, and manage follow-ups. As reception, you will primarily use it to log visitor visits, update contact information, and check for assigned tasks.',
    steps: ['Log into the CRM', 'Find your tasks and notifications', 'Update a client contact record', 'Log a visitor visit', 'Mark a task as complete'],
    estimatedMinutes: 25, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-006', title: 'Navigating Google Drive', category: 'systems',
    summary: 'Find and organise documents in the ASG Google Drive.',
    content: 'ASG uses Google Drive for document storage and sharing. You\'ll need to find shared documents, upload files, and organise content in the correct folders.',
    steps: ['Find the ASG shared drives', 'Navigate to the Reception folder', 'Upload a sample document', 'Share a document with a colleague', 'Search for documents by name and content'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-007', title: 'Using Gmail and Shared Inboxes', category: 'systems',
    summary: 'Manage the reception email account and shared inboxes.',
    content: 'The reception team manages a shared Gmail inbox. This module covers labelling, filtering, responding to common enquiries, and escalating to the right team members.',
    steps: ['Log into the reception Gmail account', 'Review the folder/label structure', 'Practice composing and sending a professional email', 'Learn how to flag and escalate emails', 'Set up email filters for common senders'],
    estimatedMinutes: 20, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-008', title: 'Client Privacy and Confidentiality', category: 'compliance',
    summary: 'Understanding privacy obligations when handling client information.',
    content: 'ASG takes client privacy seriously. This module covers the Privacy Act, handling personal information, secure document practices, and what to do if you suspect a privacy breach.',
    steps: ['Read the ASG Privacy Policy summary', 'Learn what constitutes personal information', 'Understand secure handling of documents', 'Know the procedure for reporting a privacy concern', 'Complete the acknowledgement'],
    estimatedMinutes: 20, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-009', title: 'Escalating Urgent Matters', category: 'procedures',
    summary: 'Know when and how to escalate issues to management.',
    content: 'Not all issues can be resolved at reception. This module covers what constitutes an urgent matter, who to contact, and the escalation chain. When in doubt, always ask. Never sit on a problem.',
    steps: ['Review the escalation contact list', 'Learn what constitutes urgent vs. routine', 'Practice the escalation script', 'Know when to use emergency procedures'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-010', title: 'Who to Call and Who to Email', category: 'operations',
    summary: 'A quick reference guide for who handles what at ASG.',
    content: 'Knowing who to contact for different issues saves time and ensures the right person handles each matter. This module covers the key contacts across the business and their responsibilities.',
    steps: ['Review the contacts list in the Reception Hub', 'Learn who handles IT, HR, Accounts, and Facilities', 'Know the escalation path for each department', 'Practice directing enquiries to the right person'],
    estimatedMinutes: 10, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-011', title: 'Payroll and Getting Paid', category: 'operations',
    summary: 'How timesheets, payroll, and leave requests work at ASG.',
    content: 'Timesheets are submitted fortnightly. This module covers how to submit timesheets, request leave, access payslips, and who to contact with payroll questions.',
    steps: ['Learn the pay cycle dates', 'Submit a sample timesheet', 'Understand how to request annual or sick leave', 'Find your payslips', 'Know who to contact for payroll questions'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-012', title: 'Opening Reception', category: 'procedures',
    summary: 'Step-by-step guide to opening the office for the day.',
    content: 'This module covers the complete morning opening routine including unlocking, system checks, and preparing the office for the day ahead.',
    steps: ['Arrive and disarm the security system', 'Turn on lights and adjust blinds', 'Boot up your workstation and log in', 'Follow the opening checklist in the Daily Tasks', 'Greet early arrivals and prepare for the day'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-013', title: 'Closing Reception', category: 'procedures',
    summary: 'Step-by-step guide to closing the office securely.',
    content: 'Closing procedures ensure the office is secure and ready for the next business day.',
    steps: ['Complete all end-of-day tasks in the checklist', 'Ensure all visitors have signed out', 'Lock all filing cabinets and secure documents', 'Turn off lights and non-essential equipment', 'Set the alarm and lock all entry points'],
    estimatedMinutes: 15, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-014', title: 'Printing Office Documents', category: 'operations',
    summary: 'How to use the office printers, copiers, and manage print jobs.',
    content: 'The Brisbane office uses networked multi-function printers. This module covers printing, scanning, copying, and replacing paper or toner.',
    steps: ['Learn the printer locations and network names', 'Print a test document', 'Scan a document to email', 'Replace paper in each printer', 'Know how to report a printer fault'],
    estimatedMinutes: 20, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'train-015', title: 'Handling Unfamiliar Questions', category: 'procedures',
    summary: 'What to do when you don\'t know the answer.',
    content: 'It is perfectly fine not to have every answer. The important thing is to handle unfamiliar questions professionally: acknowledge the question, never guess, and find the right person who can help. "That\'s a great question — let me find the best person to help you with that."',
    steps: ['Acknowledge the question politely', 'Never guess or make up an answer', 'Know where to find the right contact', 'Escalate when appropriate', 'Follow up to ensure the client got the answer they needed'],
    estimatedMinutes: 10, assignedStaffIds: ['reception-001'], active: true, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2025-01-01T00:00:00.000Z',
  },
];
